// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace reservation_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240709211030_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Appointment", b =>
                {
                    b.Property<Guid>("appointment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("confirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("provider_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("reserved_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("reserved_by_client_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("timeslot")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("appointment_id");

                    b.HasIndex("provider_id");

                    b.HasIndex("reserved_by_client_id");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<Guid>("client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("client_id");

                    b.ToTable("client");
                });

            modelBuilder.Entity("Provider", b =>
                {
                    b.Property<Guid>("provider_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("provider_id");

                    b.ToTable("provider");
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasOne("Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("provider_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client", "Client")
                        .WithMany()
                        .HasForeignKey("reserved_by_client_id");

                    b.Navigation("Client");

                    b.Navigation("Provider");
                });
#pragma warning restore 612, 618
        }
    }
}
